"""added backdrop_url and age_rating fields to movie

Revision ID: b8f08c1dc3d0
Revises: e66494d62f1d
Create Date: 2026-05-17 16:20:20.502837

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8f08c1dc3d0"
down_revision: Union[str, Sequence[str], None] = "e66494d62f1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movies", sa.Column("backdrop_url", sa.String(length=500), nullable=True)
    )
    op.add_column("movies", sa.Column("age_rating", sa.Integer(), nullable=True))

    op.execute("UPDATE movies SET age_rating = 0")

    op.alter_column("movies", "age_rating", existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movies", "age_rating")
    op.drop_column("movies", "backdrop_url")
    # ### end Alembic commands ###
