"""create seats table

Revision ID: e66494d62f1d
Revises: 8613588f561c
Create Date: 2026-05-17 15:56:40.716146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66494d62f1d'
down_revision: Union[str, Sequence[str], None] = '8613588f561c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('screen_id', sa.UUID(), nullable=False),
    sa.Column('row_label', sa.String(length=1), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('seat_type', sa.Enum('standard', 'vip', 'love', name='seat_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seats')
    # ### end Alembic commands ###
